### ISSUE TITLE
Code coverage incorrectly reported to coveralls as 0%

### ISSUE THREAD

**Issue by bgourlie** [huonw/travis-cargo#11]
My build can be seen here: https://travis-ci.org/bgourlie/rs-nes/jobs/72764212

Coveralls results here: https://coveralls.io/github/bgourlie/rs-nes

Not sure if I've misconfigured something, but I've read the docs pretty thoroughly.  Nothing in the build log indicates any failures, and all the tests are being run and recorded.

**Comment by vberger** [comment]
I noticed the same thing. I had a working setup, and without changing anything, my coverage dropped to 0% (see https://coveralls.io/github/vberger/silinapse ).

**Comment by vberger** [comment]
This is probably a kcov issue actually, running kcov manually on my computer and sending directly to coveralls via the `--covertalls-id=...` gives the same result.

**Comment by bgourlie** [comment]
See https://github.com/SimonKagstrom/kcov/issues/105

**Comment by vberger** [comment]
@bgourlie isn't it rather https://github.com/SimonKagstrom/kcov/issues/106 ?

**Comment by bgourlie** [comment]
You're right -- my bad :)
