### ISSUE TITLE
Add support for --verify flag of kcov

### ISSUE THREAD

**Issue by vberger** [huonw/travis-cargo#12]
See https://github.com/SimonKagstrom/kcov/issues/105 and https://github.com/rust-lang/rust/issues/27324

Apparently, the current state of rust and kcov can result in situations where kcov segfaults during the tests because of ill-placed breakpoints.

A simple workaround is to pass a `--verify` flag to kcov, as well as installing `binutils-dev` in the test environment. Having an option to activate this flag would be nice (for example one of my projects require it).

**Comment by SimonKagstrom** [comment]
To clarify, kcov itself doesn't segfault, but rather the covered process segfaults due to a breakpoint being set in the middle of an instruction (which in turn happens because the DWARF debug information is incorrectly generated).

**Comment by huonw** [comment]
Is there any downside to unconditionally passing `--verify` to kcov? I guess it might be a performance hit?

**Comment by vberger** [comment]
@huonw Yes, the extra dependency and a performance hit, that's all.
