### ISSUE TITLE
Split coveralls into coverage-collection & coverage-upload?

### ISSUE THREAD

**Issue by badboy** [huonw/travis-cargo#2]
Currently coverage is tightly coupled to coveralls.io, which is fine for opensource projects as it is free, but for other projects maybe not an option.
Collecting just the kcov output might me desirable nonetheless and invoking it from travis-cargo and possibly handling the upload somewhere else would be nice.

This would also make it possible to execute it locally for a quick overview.

**Comment by huonw** [comment]
Good idea. I've implemented [`travis-cargo coverage`](https://github.com/huonw/travis-cargo#coverage) which will collect without the upload.

I've not quite split it, since the common case is collect-and-upload and having that entirely performed by a single `travis-cargo coveralls` is nice.

**Comment by badboy** [comment]
Thanks! Exactly what I want. :)
