### ISSUE TITLE
Error on nightly compile with t-c

### ISSUE THREAD

**Issue by llogiq** [huonw/travis-cargo#23]
I tried to [travis-cargo-ify paholg's typenum crate](https://github.com/paholg/typenum/pull/4).

However, on the nightly build, I get the following [error](https://travis-ci.org/paholg/typenum/jobs/82535763):

```
Package `typenum v0.0.1 (file:///home/travis/build/paholg/typenum)` does not have these features: `unstable`
```

I may currently be too illiterate to read the docs, considering I only had two cups of coffee as of yet, but I cannot find anything of help. Could someone help me make the build pass?

**Comment by huonw** [comment]
http://huonw.github.io/blog/2015/04/helping-travis-catch-the-rustc-train/

> tc cargo ... just runs cargo, but implicitly adds --feature unstable when running the rust: nightly configuration (and --verbose by default for all configurations).

https://github.com/huonw/travis-cargo#example

> If you do not wish to define an unstable or similar feature, setting TRAVIS_CARGO_NIGHTLY_FEATURE="" should avoid errors caused by undefined features.

**Comment by llogiq** [comment]
Thanks, that did the trick. :+1:
