### ISSUE TITLE
Add support of different doc-upload targets

### ISSUE THREAD

**Issue by llogiq** [huonw/travis-cargo#24]
pagolg wants to have the docs on his personal repo, not the gh-pages branch of the project repo. I'd like to travis-cargoify his typenum crate, and this is blocking me.

**Comment by huonw** [comment]
I'm sorry but I don't understand. Do you want to upload to a different branch? Or a push to a different repo? Or something else?

**Comment by llogiq** [comment]
Push to a different repo, on the master branch. Making repo and branch overridable by either env or command arguments should do the trick.

**Comment by huonw** [comment]
Is it OK if the push completely overwrites the branch that is being pushed to?

**Comment by llogiq** [comment]
Probably not – paholg wants this in his personal github.io repo.

Thinking about it, I'm going to close this. It's too risky.
