### ISSUE TITLE
add sudo: false to example .travis.yml

### ISSUE THREAD

**Issue by gnzlbg** [huonw/travis-cargo#25]
To run in the new container infrastructure by default.

**Comment by huonw** [comment]
I was under the impression that this was travis's default, at least for new projects.

**Comment by gnzlbg** [comment]
Weird, that is what they said http://docs.travis-ci.com/user/workers/container-based-infrastructure/ but that day I created a new rust repo and got from travis a "warning" stating that I should write `sudo: false` to have it run in the new container infrastructure.
