### ISSUE TITLE
Error when running stable build after rust stable upgraded to 1.4 

### ISSUE THREAD

**Issue by PhnxRbrn** [huonw/travis-cargo#30]
I received the following error after rust stable upgrade

the manifest-path must be a path to a Cargo.toml file

The command "travis-cargo build &&

travis-cargo test &&

travis-cargo bench &&

travis-cargo --only stable doc

" exited with 101.

**Comment by PhnxRbrn** [comment]
Note that it still works in new beta 1.5

**Comment by Ygg01** [comment]
I had the same issue. Nightly and beta work ok, but stable breaks.

**Comment by huonw** [comment]
Sorry! I have a fix, just making sure it works on all Rust versions (14 travis builds takes a while...). I'll be publishing it as 0.1.10 soon.
