### ISSUE TITLE
doc-upload not working

### ISSUE THREAD

**Issue by ryantaylor** [huonw/travis-cargo#31]
doc-upload doesn't seem to be working. I get this when I try to use it no matter what, even if I have `name = "something"` in my Cargo.toml manifest file:

```
[0K$ travis-cargo doc-upload
error: uploading docs for package with no librarytravis_time:end:1b99672e:start=1446255386016247184,finish=1446255386102807024,duration=86559840
[0Ktravis_fold:end:after_success.1
```

I also checked the Travis logs for the recent travis-cargo build tests and it doesn't seem to run there either:

```
+travis-cargo doc-upload
+travis-cargo coverage -m target/coverage -- --features remove-failing
Running: sudo apt-get install libcurl4-openssl-dev libelf-dev libdw-dev cmake
```

It seems to skip right past the `travis-cargo doc-upload` line without doing anything.

**Comment by huonw** [comment]
The package needs to have a library, e.g. either an explicit `[lib]` section, or `src/lib.rs`.

**Comment by ryantaylor** [comment]
I have that:

```
[lib]
name = "vault"
```
Still doesn't work for me.

**Comment by huonw** [comment]
Is your project/the travis builds public? Could I take a look?
