### ISSUE TITLE
travis-cargo leaking credentials - if authentication fails

### ISSUE THREAD

**Issue by colin-kiegel** [huonw/travis-cargo#36]
travis-cargo will leak credentials in public travis log if authentication fails
fatal: Authentication failed for 'https://XXXXXXXXXXXX@github.com/some/project'

You may say it's not bad, because the credentials must be wrong - but I think it's still a security issue.

Please leave a note in your manual to either redirect output from the log (via shell-pipes) or some other kind of warning note.

**Comment by huonw** [comment]
Hm, this sounds unfortunate, however I'm unclear about exactly when this happens (e.g. what subcommands?).

**Comment by colin-kiegel** [comment]
```
    travis-cargo --only stable doc-upload    
 
uploading docs...
Cloning into 'ghp-import'...
remote: Counting objects: 228, done.
remote: Total 228 (delta 0), reused 0 (delta 0), pack-reused 228
Receiving objects: 100% (228/228), 64.10 KiB | 0 bytes/s, done.
Resolving deltas: 100% (113/113), done.
Checking connectivity... done.
remote: Invalid username or password.
fatal: Authentication failed for 'https://XXXXXXXXXXXX@github.com/some/project'
```

The reason was, that I mixed up the travis application oauth token with the personal access token. Of course I have revoked and recreated my application token after that.

Now I append `2> /dev/null` - untested, but I think it should work.
```
    travis-cargo --only stable doc-upload 2> /dev/null # anti-credential leakage
    
uploading docs...
```

**Comment by huonw** [comment]
Ah, ok.

What do you think about filtering the token (since travis-cargo knows it) from the output? This ensures that it is still easy to debug problems, since the output is there, but also ensures that the secret never appears, e.g. your example might look like:

```
    travis-cargo --only stable doc-upload    

uploading docs...
Cloning into 'ghp-import'...
remote: Counting objects: 228, done.
remote: Total 228 (delta 0), reused 0 (delta 0), pack-reused 228
Receiving objects: 100% (228/228), 64.10 KiB | 0 bytes/s, done.
Resolving deltas: 100% (113/113), done.
Checking connectivity... done.
remote: Invalid username or password.
fatal: Authentication failed for 'https://<GH_TOKEN removed>@github.com/some/project'
```

**Comment by colin-kiegel** [comment]
Sounds perfect. :-)
