### ISSUE TITLE
why run `cargo bench` only using nightly?

### ISSUE THREAD

**Issue by florianjacob** [huonw/travis-cargo#44]
The readme says:
> automatically only run cargo bench when supported (nightly compiler)

Is that still true? `cargo bench` seemed to work just fine with stable rust (1.6). Are there any other reasons why `cargo bench` should run only on nightly?

The current behaviour causes issues like https://github.com/rprotasov/rune/issues/7  and needs workarounds like #33.

**Comment by huonw** [comment]
The `test` crate and hence the `test::Bencher` type needed from it are unstable, and hence can only be used with a nightly compiler.

**Comment by huonw** [comment]
See, for instance, https://github.com/huonw/travis-cargo/issues/5, or the end of [the Example section of the README](https://github.com/huonw/travis-cargo#example).

**Comment by florianjacob** [comment]
Ok, now I understand, thanks for your time. :smile:
