### ISSUE TITLE
coveralls upload sets wrong source path

### ISSUE THREAD

**Issue by llogiq** [huonw/travis-cargo#47]
See https://coveralls.io/github/llogiq/optional?branch=master for example, the `src/` subdir is missing.

**Comment by llogiq** [comment]
I solved the issue at the source view on coveralls.io (there's a text input one can write src/ into).

**Comment by Wilfred** [comment]
I hit this too. Why did you close this? AFAICS it's a genuine bug, or would at least merit a mention the readme.
