### ISSUE TITLE
No way to stop travis-cargo from adding a feature flag on nightly

### ISSUE THREAD

**Issue by Aatch** [huonw/travis-cargo#5]
Not a huge problem, since you can always just add a dummy feature to `Cargo.toml` but if you don't actually need a feature for unstable/nightly, it's a bit annoying that you can't tell travis-cargo that you don't want a flag at all.

**Comment by huonw** [comment]
You can set `TRAVIS_CARGO_NIGHTY_FEATURE=""` which will remove this problem. (I'm still unsure about whether I want to implement a "real" way to disable it or not.)

**Comment by Aatch** [comment]
I tried that, it treats an empty string as it not being there (I think) and uses the default.

**Comment by vberger** [comment]
A workaround would be setting the variable to `" "`, which cargo interprets as an empty features list.

However, there are also situations where cargo simply refuses to get a `--features` flag.
I have a project consisting of several libs in the same git repo, that I used to test using commands like
```
cargo test -p foo
```
But after migrating to travis-cargo, cargo complains that
```
features cannot be modified when the main package is not being built
```
It would really be nice to have a way to completely disable passing the `--features` flag.

**Comment by huonw** [comment]
@vberger the `-p` problem is covered by #14 (which I'm pushing a fix for in the next few minutes).
