### ISSUE TITLE
`travis-cargo coveralls` fails when testing subcrate compiled as dylib

### ISSUE THREAD

**Issue by euclio** [huonw/travis-cargo#52]
See [the most recent build](https://travis-ci.org/Hoverbear/rust-rosetta/builds/121140610#L6383) of [Hoverbear/rust-rosetta](https://github.com/Hoverbear/rust-rosetta).

travis-cargo is trying to run kcov on [this subcrate](https://github.com/Hoverbear/rust-rosetta/tree/master/src/use_another_language_to_call_a_function), but it can't find the shared object generated by cargo.

.travis.yml found [here](https://github.com/Hoverbear/rust-rosetta/blob/master/.travis.yml).

`travis-cargo coveralls` has been failing since the crate was committed, but went unnoticed because the `coveralls` subcommand returns 0 even if it fails.

**Comment by euclio** [comment]
I don't really know much about linking, can we just add `target/debug/deps` to the `LD_LIBRARY_PATH` when running kcov?

**Comment by euclio** [comment]
Seems to have worked: Hoverbear/rust-rosetta#487

**Comment by huonw** [comment]
@euclio thanks for diagnosing a fix!
