### ISSUE TITLE
Coverage seems to be broken.

### ISSUE THREAD

**Issue by dragostis** [huonw/travis-cargo#54]
I tried using this [configuration](https://github.com/dragostis/pest/blob/master/.travis.yml), but I'm getting `kcov` [usage](https://travis-ci.org/dragostis/pest/jobs/133119571):

```
Uploading coverage
Usage: kcov [OPTIONS] out-dir in-file [args...]
Where [OPTIONS] are
 -h, --help              this text

...
```

**Comment by dragostis** [comment]
I think it was a `kcov` issues, as it's working right now.

**Comment by panicbit** [comment]
Doesn't seem to work now though. https://travis-ci.org/panicbit/orf/builds/135319364#L805
